### ISSUE TITLE
Active stake show on pool page is incorrect

### ISSUE THREAD

**Issue by 36thchambersoftware** [cexplorer/cexplorer.io#39]
**Describe the bug**
On my pool's page it shows the active stake as zero. The live stake and pledge are both showing correctly. 

**To Reproduce**
1. Go to [ 'HERE'](https://cexplorer.io/pool/pool19peeq2czwunkwe3s70yuvwpsrqcyndlqnxvt67usz98px57z7fk)
2. Scroll down to 'Active Stake'
4. See amount listed as zero.

**Expected behavior**
The active stake should be shown as roughly 7-8K ada. 

**Screenshots**
![Screenshot 2023-02-22 at 7 43 15 AM](https://user-images.githubusercontent.com/1509069/220637261-19dd799b-3393-460c-963c-690ed1caea5b.png)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser: Chrome, Brave, Safari
 - Version: All

**Comment by gusosborne** [comment]
Happening to me again as well. I am too afraid to increase my pledge until this is resolved. I reverted and decreased my declared pledge to the previous amount. 

Not sure if Cexplorer is getting stuck- or maybe it’s just taking much longer than it should to update actual pledged amounts..?
Seems like OP is being affected by multiple bugs here. 

OP’s pool “PREEB” is still not able to be located in yoroi or delegated to, because of this bug:

![AC7893D3-289D-49B4-9A2E-4792960DB44A](https://user-images.githubusercontent.com/25893043/222282410-1246f99d-1562-42d3-9f6d-87f72ce9ed67.jpeg)

**Comment by gusosborne** [comment]
PREEB is still blacklisted from yoroi / cexplorer for this “pledge not met bug”, it’s going on a month now. 
PLEDGE is met - Live: 9,296 ₳ - Declared: 1,000 ₳

Here’s another report of the same bug:
https://github.com/cexplorer/cexplorer.io/issues/13#issuecomment-1244577692

Simply showing ALL pools in a search (whether cexplorer thinks they have met a pledge or not) would fix this issue. 

Im thinking we should probably loop emurgo / yoroi in at this point.

**Comment by gusosborne** [comment]
Same bug now with “CSK”
PLEDGE is met - Live: 10,401 ₳ - Declared: 10,000 ₳
Cannot be found in yoroi

**Comment by gusosborne** [comment]
Another report, same bug with “ISYG” pool:

https://github.com/cexplorer/cexplorer.io/issues/38#issuecomment-1500769090

PLEDGE is met - Live: 29,403 ₳ - Declared: 10,000 ₳

**ISYG is currently blacklisted from yoroi, due to same unaddressed cexplorer bug.** 

![5BF3E1FF-EFF3-44AA-9EF4-5D365CE56969](https://user-images.githubusercontent.com/25893043/230722993-990e47d8-9e34-4315-a2f1-52c4108f9cad.jpeg)

Please fix this.

**Comment by IndieStakeHub** [comment]
Hi there,

Same issue with our pool IndieStakeHub : pool13g5ftmgqktfja04xwyd7yte8p0arelzyygndyfjr798vsx0cd6f
Active stake is 0 but no problem to find it in Yoroi.

See ticket https://github.com/cexplorer/cexplorer.io/issues/53
